# ----------------------------
# Makefile Options
# ----------------------------

NAME = TEST
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz
EXTRA_CPPSOURCES = ../../test_utils.cpp ../../../src/dictionary.cpp ../../../src/word.cpp

# ----------------------------

include $(shell cedev-config --makefile)
